---
- hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    
    - name: Add Kubernetes Signing Key
      shell: |
              curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg --batch --yes

    - name: Add Software Repositories
      shell: |
              echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes.gpg] http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list
              sudo apt update

    - name: Install Kubernetes Tools
      shell: |
              sudo apt install kubeadm kubelet kubectl -y

    - name: Disabling swap
      shell: |
              sudo swapoff -a
              sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Creating a configuration file for containerd
      file:
        path: "/etc/modules-load.d/containerd.conf"
        state: "touch"

    - name: setting up pre-requisites for containerd
      blockinfile:
        path: "/etc/modules-load.d/containerd.conf"
        block: |
              overlay
              br_netfilter

    - name: loading required modules
      shell: |
              sudo modprobe overlay
              sudo modprobe br_netfilter

    - name: create file to configure Kubernetes networking 
      file:
        path: "/etc/sysctl.d/kubernetes.conf"
        state: "touch"

    - name: configure Kubernetes networking
      blockinfile:
        path: "/etc/sysctl.d/kubernetes.conf"
        block: |
              net.bridge.bridge-nf-call-iptables = 1
              net.ipv4.ip_forward = 1
              net.bridge.bridge-nf-call-ip6tables = 1


    - name: Reload the configuration
      command: sudo sysctl --system